### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by TomPed**
Anything I need to add for the FAQ or caveats?

### CODE REVIEW

**Comment by stevepeak** [comment]
There are two different strategies for producing coverage reports.

#### plist coverage `default`
This technique will upload the plist containing coverage data.
- 👎 This format includes all files and projects, which can be very large causing issues processing.
- 👍 Partial coverage data is included, which looks beautiful in Codecov UI

Enabled by default.

#### llvm-cov
This technique will run `llvm-cov` which produces coverage reports.
- 👍 You can specify specific packages to run coverage against (see below)
- 👎 No partial coverage data

To enable

```sh
bash <(curl -s https://codecov.io/bash) -X xcodellvm
# - or -
bash <(curl -s https://codecov.io/bash) -J '^MyPackage$'
# ^^ will enable xcodellvm and only process MyPackage coverage
```

**Comment by TomPed** [comment]
Updated.

**Comment by TomPed** [comment]
Any idea how to fix build?

**Comment by thomasrockhu** [comment]
@TomPed given that this is a `README` change, I went ahead and pushed the change here https://github.com/codecov/example-swift/pull/26.  Thanks again!

**Pull request closed without merging**
